
services:
  db:
    image: mysql:8.0
    container_name: starmall_db
    restart: unless-stopped
    environment:
      # 【重点修改这里】：必须和 .env 里配置的密码库名完全一致
      MYSQL_ROOT_PASSWORD: Xy20190411    
      MYSQL_DATABASE: thumbs_mall
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    # 永久写入：强制指定容器的字符集
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;'

  backend:
    build:
      context: ./backend
    container_name: starmall_backend
    restart: unless-stopped
    # 之前在 yml 里写的 environment 可以删掉了，直接让它读取 backend/.env 文件更干净
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "28001:28001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: starmall_frontend
    restart: unless-stopped
    ports:
      - "28000:80"   
    depends_on:
      - backend

volumes:
  db_data:
